name: search_task
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  domain:
    path: ./domain
  core:
    path: ./core
  data:
    path: ./data
  navigation:
    path: ./navigation
  cupertino_icons: ^1.0.8
  flex_color_scheme: ^8.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  build_runner: ^2.4.13
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
