name: search
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../../core
  domain:
    path: ../../domain
  navigation:
    path: ../../navigation
  easy_infinite_pagination: ^0.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  build_runner: ^2.4.13
  auto_route_generator: ^9.0.0
